import { BusinessProfile, Customer, Employee, GroceryItem, Transaction } from '../types';

export const INITIAL_BUSINESS_PROFILE: BusinessProfile = {
  shopName: 'Al Noor Grocery & Supermarket LLC',
  shopNameArabic: 'بقالة النور وشوبرماركت ذ.م.م',
  trn: '100456789012345',
  ownerName: 'Mohiyuddin',
  phone: '+971 50 847 2910',
  address: 'Shop #12, Sheikh Rashid Building, Al Karama, Dubai, UAE',
  salesThisMonth: 14850.00,
  expensesThisMonth: 4200.00,
  rollingTurnover: 215000,
  vatThreshold: 375000,
  voluntaryThreshold: 187500,
  whatsappReminders: true,
  language: 'English',
  currency: 'AED',
};

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    name: 'Walk-in Customer',
    phone: 'N/A',
    creditBalance: 0,
    totalSpent: 4250.00,
    lastPurchaseDate: 'Today',
  },
  {
    id: 'cust-2',
    name: 'Tariq Al Mansoori',
    phone: '+971 50 123 4567',
    email: 'tariq.m@gmail.com',
    address: 'Apt 402, Karama Crown',
    creditBalance: 145.00, // Owes 145 AED (Khata)
    totalSpent: 1850.00,
    lastPurchaseDate: 'Today, 10:42 AM',
  },
  {
    id: 'cust-3',
    name: 'Rahul Sharma',
    phone: '+971 55 987 6543',
    address: 'Bldg 15, Street 22, Karama',
    creditBalance: 80.00,
    totalSpent: 920.00,
    lastPurchaseDate: 'Yesterday',
  },
  {
    id: 'cust-4',
    name: 'Fatima Al Hashmi',
    phone: '+971 52 444 3322',
    trn: '100987654321000',
    creditBalance: 0,
    totalSpent: 3400.00,
    lastPurchaseDate: '3 days ago',
  },
  {
    id: 'cust-5',
    name: 'Mohammed Usman',
    phone: '+971 56 321 8899',
    creditBalance: 210.00,
    totalSpent: 1200.00,
    lastPurchaseDate: 'Yesterday',
  },
];

export const INITIAL_GROCERY_ITEMS: GroceryItem[] = [
  {
    id: 'item-1',
    name: 'India Gate Basmati Rice 5kg',
    nameArabic: 'أرز أبيض 5 كجم',
    category: 'Grocery',
    price: 38.50,
    unit: 'bag',
    stockQty: 24,
    barcode: '890123456701',
    icon: 'rice_bowl',
  },
  {
    id: 'item-2',
    name: 'Al Rawabi Fresh Milk 2L',
    nameArabic: 'حليب طازج الروابي 2 لتر',
    category: 'Dairy & Fresh',
    price: 11.00,
    unit: 'pcs',
    stockQty: 18,
    barcode: '629100100201',
    icon: 'local_drink',
  },
  {
    id: 'item-3',
    name: 'Al Ain Mineral Water 6x1.5L',
    nameArabic: 'مياه العين 6 × 1.5 لتر',
    category: 'Beverages',
    price: 8.50,
    unit: 'pack',
    stockQty: 40,
    barcode: '629110000101',
    icon: 'water_drop',
  },
  {
    id: 'item-4',
    name: 'Lipton Yellow Label Tea 100 Bags',
    nameArabic: 'شاي ليبتون 100 كيس',
    category: 'Grocery',
    price: 16.25,
    unit: 'box',
    stockQty: 15,
    barcode: '871256612345',
    icon: 'coffee',
  },
  {
    id: 'item-5',
    name: 'Fresh Tomatoes 1kg',
    nameArabic: 'طماطم طازجة 1 كجم',
    category: 'Dairy & Fresh',
    price: 4.50,
    unit: 'kg',
    stockQty: 50,
    icon: 'nutrition',
  },
  {
    id: 'item-6',
    name: 'Local Fresh Eggs 30 Pack',
    nameArabic: 'بيض طازج 30 حبة',
    category: 'Dairy & Fresh',
    price: 18.00,
    unit: 'pack',
    stockQty: 12,
    icon: 'egg',
  },
  {
    id: 'item-7',
    name: 'Lurpak Salted Butter 200g',
    nameArabic: 'زبدة لورباك 200 جم',
    category: 'Dairy & Fresh',
    price: 12.50,
    unit: 'pcs',
    stockQty: 20,
    icon: 'bakery_dining',
  },
  {
    id: 'item-8',
    name: 'Al Kabeer Chicken Nuggets 500g',
    nameArabic: 'ناجتس دجاج الكبير 500 جم',
    category: 'Grocery',
    price: 19.75,
    unit: 'pack',
    stockQty: 14,
    icon: 'fastfood',
  },
  {
    id: 'item-9',
    name: 'Nutella Hazelnut Spread 400g',
    nameArabic: 'نوتيلا 400 جم',
    category: 'Snacks & Sweets',
    price: 17.50,
    unit: 'pcs',
    stockQty: 10,
    icon: 'cookie',
  },
  {
    id: 'item-10',
    name: 'Tide Washing Powder 2.5kg',
    nameArabic: 'مسحوق غسيل تايد 2.5 كجم',
    category: 'Household',
    price: 26.00,
    unit: 'box',
    stockQty: 8,
    icon: 'cleaning_services',
  },
  {
    id: 'item-11',
    name: 'Dettol Antiseptic Liquid 500ml',
    nameArabic: 'سائل ديتول 500 مل',
    category: 'Personal Care',
    price: 15.00,
    unit: 'pcs',
    stockQty: 16,
    icon: 'sanitizer',
  },
  {
    id: 'item-12',
    name: 'Fresh Bananas 1kg',
    nameArabic: 'موز طازج 1 كجم',
    category: 'Dairy & Fresh',
    price: 5.50,
    unit: 'kg',
    stockQty: 30,
    icon: 'eco',
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-1',
    type: 'sale',
    invoiceNumber: 'INV-2026-0104',
    title: 'Grocery Order - Tariq Al Mansoori',
    customerId: 'cust-2',
    customerName: 'Tariq Al Mansoori',
    customerPhone: '+971 50 123 4567',
    items: [
      { itemId: 'item-1', name: 'India Gate Basmati Rice 5kg', unitPrice: 38.50, quantity: 1, unit: 'bag', itemDiscount: 0, total: 38.50 },
      { itemId: 'item-2', name: 'Al Rawabi Fresh Milk 2L', unitPrice: 11.00, quantity: 2, unit: 'pcs', itemDiscount: 0, total: 22.00 },
      { itemId: 'item-6', name: 'Local Fresh Eggs 30 Pack', unitPrice: 18.00, quantity: 1, unit: 'pack', itemDiscount: 0, total: 18.00 },
    ],
    subtotal: 78.50,
    discountType: 'fixed',
    discountValue: 3.50,
    discountAmount: 3.50,
    vatAmount: 3.75, // (78.50 - 3.50) * 0.05
    amount: 78.75,
    category: 'Grocery',
    paymentMethod: 'Credit / Khata',
    date: 'Today, 10:42 AM',
    rawDate: new Date().toISOString(),
    time: '10:42 AM',
    notes: 'Delivered to Apt 402',
  },
  {
    id: 'tx-2',
    type: 'expense',
    invoiceNumber: 'EXP-2026-0089',
    title: 'Al Madina Wholesalers Stock Purchase',
    subtotal: 1142.86,
    discountAmount: 0,
    vatAmount: 57.14,
    amount: 1200.00,
    category: 'Stock',
    merchant: 'Al Madina Wholesalers LLC',
    paymentMethod: 'Bank Transfer',
    date: 'Today, 09:15 AM',
    rawDate: new Date().toISOString(),
    time: '09:15 AM',
    notes: 'Bulk stock of Rice, Milk, and Oil',
  },
  {
    id: 'tx-3',
    type: 'sale',
    invoiceNumber: 'INV-2026-0103',
    title: 'Walk-in Snacks & Milk',
    customerId: 'cust-1',
    customerName: 'Walk-in Customer',
    items: [
      { itemId: 'item-2', name: 'Al Rawabi Fresh Milk 2L', unitPrice: 11.00, quantity: 1, unit: 'pcs', itemDiscount: 0, total: 11.00 },
      { itemId: 'item-9', name: 'Nutella Hazelnut Spread 400g', unitPrice: 17.50, quantity: 1, unit: 'pcs', itemDiscount: 0, total: 17.50 },
    ],
    subtotal: 28.50,
    discountAmount: 0,
    vatAmount: 1.43,
    amount: 29.93,
    category: 'Dairy & Fresh',
    paymentMethod: 'Cash',
    date: 'Today, 08:20 AM',
    rawDate: new Date().toISOString(),
    time: '08:20 AM',
  },
  {
    id: 'tx-4',
    type: 'sale',
    invoiceNumber: 'INV-2026-0102',
    title: 'Bulk Order - Fatima Al Hashmi',
    customerId: 'cust-4',
    customerName: 'Fatima Al Hashmi',
    items: [
      { itemId: 'item-1', name: 'India Gate Basmati Rice 5kg', unitPrice: 38.50, quantity: 3, unit: 'bag', itemDiscount: 0, total: 115.50 },
      { itemId: 'item-3', name: 'Al Ain Mineral Water 6x1.5L', unitPrice: 8.50, quantity: 4, unit: 'pack', itemDiscount: 0, total: 34.00 },
      { itemId: 'item-10', name: 'Tide Washing Powder 2.5kg', unitPrice: 26.00, quantity: 2, unit: 'box', itemDiscount: 0, total: 52.00 },
    ],
    subtotal: 201.50,
    discountType: 'percent',
    discountValue: 10,
    discountAmount: 20.15,
    vatAmount: 9.07,
    amount: 190.42,
    category: 'Grocery',
    paymentMethod: 'Card',
    date: 'Yesterday, 04:30 PM',
    rawDate: new Date(Date.now() - 86400000).toISOString(),
    time: '04:30 PM',
  },
  {
    id: 'tx-5',
    type: 'expense',
    invoiceNumber: 'EXP-2026-0088',
    title: 'Shop Rent - Karama Crown Bldg',
    subtotal: 2380.95,
    discountAmount: 0,
    vatAmount: 119.05,
    amount: 2500.00,
    category: 'Rent',
    merchant: 'Al Wasl Real Estate LLC',
    paymentMethod: 'Bank Transfer',
    date: 'Yesterday, 10:00 AM',
    rawDate: new Date(Date.now() - 86400000).toISOString(),
    time: '10:00 AM',
  },
];

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-1',
    name: 'Mohiyuddin (Owner / Manager)',
    role: 'Store Admin',
    phone: '+971 50 847 2910',
    pin: '1234',
    salesCountToday: 14,
    totalSalesToday: 1845.50,
    activeShift: true,
    avatarColor: '#007a3d',
  },
  {
    id: 'emp-2',
    name: 'Rashid Khan',
    role: 'Senior Cashier',
    phone: '+971 55 432 1098',
    pin: '0000',
    salesCountToday: 28,
    totalSalesToday: 3120.00,
    activeShift: true,
    avatarColor: '#0284c7',
  },
  {
    id: 'emp-3',
    name: 'Bilal Ahmed',
    role: 'Junior Cashier',
    phone: '+971 52 765 4321',
    pin: '1111',
    salesCountToday: 12,
    totalSalesToday: 950.25,
    activeShift: false,
    avatarColor: '#d97706',
  },
];

export const LOGO_URL = "https://lh3.googleusercontent.com/aida-public/AB6AXuAtzMYcs342SDk7RVeKauKuwli2fKS00q_X9n0qGnxNj53huGRPTSspp6CbEOGvqt1AjMPqa08kq3Igp-31B8w3uUgfBsFYIm27UO7bMbD9DXazM9N2Aw5U7Gus7-QY02HdfahGlY61EEhFrpNuMT9srPX3YJVhTZlEfEK7rE2E-2sC6IWg2T9lOKWo6kktPlbkgjvBwIPM_54Rki27looKO61vHYZLP8ivT-gccpCZ6blC_AXWFUuK-w";

export const CAMERA_BG_URL = "https://lh3.googleusercontent.com/aida-public/AB6AXuCaSHb9XBVwb-_2rPTevv8SUI4AD4XE46hEBhFPsUb-LS8Hj7VU3QJgcBKUWrG5b7d30k9NC_T0CI7AiG81GyEXYe1YWXRrejp5zWJpFtPT5R9MI07a-8Bl5KSwKg884dKSoP5zm0f640UJ_LZ_M6s-4U_2JNhx3OS9BFI290zKy6seNVhb8w2SONMmlKEd8_q9SeCCHXxJAwBvCbCKNavKpSN39wWa1akqVwJacaJOdVGdww3I1asE5g";
export const RECEIPT_THUMB_URL = "https://lh3.googleusercontent.com/aida-public/AB6AXuAuK88lNoO9KLZt_wBtABYvdUWIuWc0Q5UR-YmYLT50S5q9rcqcCd9KD4QRjYEVAbT2-8ggC8vmYL7hff93sFXKnsBYGOVuJzdeLtT7RJycrutl-I3pqktrcIxZV12MA1z-gPg7uFWcchnTN-ldtlbr7qS01duqJvIHI6BqclRvZuEYKOBF2wQ3KJFQHYr8UKGJsB2PZGCnAURe8OsdwVybzyYSx5LQ8FWz5g9Sfv9hwvDIo1hgYCUQTQ";
